import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: prod ? "es2022" : "es2024",
	logLevel: "info",
	treeShaking: true,
	sourcemap: prod ? false : "inline",
	outfile: prod ? "main.js" : "dist/main.js",
	minify: prod ? true : false,
	dropLabels: prod ? ["devel"] : undefined,
	tsconfig: "tsconfig.json"
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}